# Generated by Django 2.1 on 2021-04-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Name')),
                ('price', models.FloatField(default=0, verbose_name='Price')),
                ('description', models.TextField(verbose_name='Description')),
                ('count', models.IntegerField(verbose_name='Count')),
                ('is_active', models.BooleanField(default=False, verbose_name='Status')),
            ],
        ),
    ]
