# Generated by Django 2.1 on 2021-04-08 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='namee',
            new_name='name',
        ),
    ]
